// Privacy Policy — v1 PUBLISHABLE.
// Source of truth: docs/legal/politique-confidentialite-v1.md (publishable body ONLY;
// the source's internal appendices are NEVER reproduced here).
// Faithful translation of the frozen FR text — same article structure. Source tables
// (art. 3, art. 6) rendered as lists (the MarkdownText renderer has no table support).
import { LEGAL_VERSION, LEGAL_UPDATED_AT } from './meta'

export const privacyEn = `# Privacy Policy

**Last updated: ${LEGAL_UPDATED_AT}** · Version ${LEGAL_VERSION}

## 1. Who is responsible for your data?

The application is provided to your gym by **Nexxia** — Antoine Monie, a Belgian sole trader, company number (BCE) **BE 1024.997.119**, Rue Grande Bruyère 6 B1, 4840 Welkenraedt, Belgium — publisher of the **Viniz** platform.

- **Your gym** (whose full identity is shown in the application and in its own terms) is the **data controller** for your member data: it decides why your data is collected (managing your bookings, payments and membership).
- **Nexxia** acts as a **data processor**: it hosts and processes this data on behalf of your gym, on its instructions, and is the controller for data strictly related to the platform's technical operation.

For any question about your data: **support@viniz.app** or directly with your gym.

## 2. What data do we collect?

**Account data** (provided by you at sign-up or in your profile): last name, first name, email address, password (stored in irreversibly hashed form), phone number, date of birth, gender, postal address, profile picture, preferred language, emergency contact (name and phone).

**Usage data** (generated by your activity): class bookings (including waitlists and cancellations), credits and subscriptions, attendance history and unreported absences, notifications sent and notification preferences.

**Payment data**: amount, plan purchased, date, status and transaction reference. **Your banking details (card, IBAN) never pass through our systems**: they are handled exclusively by our payment provider Mollie (see art. 6).

**Health data (optional)**: if you or your gym record medical information (conditions, activity restrictions, medical certificate), it is **encrypted** in our databases and accessible only to your gym's authorised staff. See art. 4.

**Technical data**: your device's push notification identifier, last-connection timestamp. The application collects **no geolocation data** and includes **no advertising trackers**.

## 3. Why and on what legal basis?

- **Account management, bookings, waitlists, subscriptions and credits** — Performance of the contract.
- **Payment processing and invoicing** — Performance of the contract + legal obligation (accounting).
- **Service-related notifications (spot freed up, class reminders, confirmations)** — Performance of the contract.
- **Enforcement of gym rules (no-show, penalties, suspension)** — Legitimate interest of the gym.
- **Marketing communications** — Consent (dedicated opt-in, withdrawable at any time).
- **Health data** — Explicit consent (GDPR art. 9.2.a).
- **Platform security (technical logs)** — Legitimate interest of the publisher.

## 4. Health data — enhanced protection

Medical information is a **special category of data** (GDPR art. 9). Our safeguards: it is **optional**, **encrypted** in the database (notes and conditions are never stored in clear text), accessible only to your gym's authorised staff, never used for any purpose other than your safety during classes, and **permanently erased** when your account is deleted (it is not kept in anonymised form). If your gym requires a medical certificate for certain activities, it is kept with its expiry date and subject to the same protections.

## 5. How long do we keep your data?

- **Active account**: for as long as your account exists.
- **Account deletion** (available in the app, Profile → Delete my account): your personal data is **anonymised immediately** (name, email, phone, address, photo replaced), your health data **erased**, and your login permanently disabled. Your email address becomes usable again for a new account.
- **Accounting and tax data** (payments, invoices): kept for **10 years** from 1 January of the year following the financial year concerned, in accordance with the retention periods applicable to VAT and income tax (Belgian Act of 20 November 2022, in force since 1 January 2023). Accounting books and journals are subject to a **7-year** period under accounting law.
- **These records keep your identity, and we cannot strip it from them**: an invoice must identify its customer to have evidential value. They are used for no purpose other than compliance with these legal obligations, and access to them is restricted.
- **Booking history**: kept in anonymised form for statistical purposes for the gym (occupancy rates), with no link to your identity.

## 6. Who has access to your data?

**Your gym**: the manager and authorised staff access the data of members of their gym only (strict per-gym isolation at the database level).

**Our technical sub-processors**, each limited to its function:

- **Supabase** — Database and infrastructure hosting · Processes all account, usage, payment and health data · European Union (Paris, France).
- **Mollie B.V.** — Payment processing · Processes billing identity and transaction data; sole recipient of your banking details (Netherlands, DNB-licensed) · EU.
- **Resend** — Sending of transactional emails · Processes your email address, first name and the message content · European Union (Ireland).
- **Vercel Inc.** — Hosting of the dashboard used by your gym · Processes, on display, the account, booking and payment data of that gym's members · United States (standard contractual clauses).
- **PostHog Inc.** — Product usage measurement, for improvement purposes · Processes a technical account identifier and usage events (screens viewed, actions); **no health data, no message content** · Hosted in the European Union (Germany); provider established in the United States (standard contractual clauses).
- **Functional Software Inc. (Sentry)** — Technical error logging, to diagnose failures · Processes a technical account identifier and the technical context of the error · Ingested in the European Union (Germany); provider established in the United States (standard contractual clauses).
- **Expo / Apple** — Delivery of push notifications · Processes a device token and the notification content · EU/United States (standard contractual clauses).

**Sign in with Google or Apple** (optional): if you choose this sign-in method, Google Ireland Ltd or Apple Inc. passes us your email address and name. Those companies then act as **independent controllers** for the authentication step — they are not our sub-processors — and their own privacy policies apply to it.

We do **not sell or rent** your data to anyone. No data is shared with third parties for advertising purposes.

## 7. Transfers outside the European Union

Your data is hosted and processed in the European Union: database in Paris, emails in Ireland, usage measurement and error logging in Germany.

Some providers are, however, established in the **United States** and may access the data as part of operating their service: **Vercel** (dashboard hosting), **PostHog** and **Sentry** (whose hosting remains European), as well as **Expo** and **Apple** for push notification delivery. These transfers are governed by the mechanisms provided in Chapter V of the GDPR (standard contractual clauses, EU-US Data Privacy Framework where applicable).

## 8. Your rights

In accordance with the GDPR, you have the following rights:

- **Access and portability**: request a copy of your data from the app (Profile → Export my data) or by email.
- **Rectification**: edit your information directly in your profile.
- **Erasure**: delete your account directly in the app (see art. 5). Restriction: if a subscription with a commitment is ongoing, deletion is possible at its end.
- **Withdrawal of consent**: disable marketing communications in your preferences at any time.
- **Objection and restriction**: contact us at support@viniz.app.
- **Complaint**: you may lodge a complaint with the **Data Protection Authority** (APD/GBA), rue de la Presse 35, 1000 Brussels — www.autoriteprotectiondonnees.be.

We respond to any request within a maximum of one month.

## 9. Security

Measures in place: encryption of communications (HTTPS/TLS), specific encryption of health data, per-gym data isolation at the database level (database access rules), secrets and payment tokens stored in an encrypted vault, passwords subject to a strength policy, access logging. As no system is infallible, we undertake to notify the DPA and the persons concerned in the event of a data breach under the conditions set out in Articles 33-34 of the GDPR.

## 10. Minors

The application is intended for persons **aged 16 or over**. Registration of a minor under 16 requires the consent of their legal guardian and acceptance by the gym, subject to the gym's own conditions. If we find that an account has been created in breach of this rule, it will be deleted.

## 11. Changes to this policy

Any substantial change will be notified to you in the application before it takes effect, with the update date at the top of this document. The version in force can be consulted at any time at **viniz.app/legal/privacy** and in the app.

## 12. Contact

**Publisher / processor**: Nexxia (Antoine Monie) — Rue Grande Bruyère 6 B1, 4840 Welkenraedt, Belgium — BCE BE 1024.997.119 — support@viniz.app

**Data controller (your gym)**: see your gym's information in the application.
`
